<p>Steps will pass or fail based on the error code that is raised from the processes launched within the step and how the shell has been configured to handle errors. You can see some of the linux shell configuration that we apply to each shell that runs a step in the job step output.</p>
<p><img src="https://support.circleci.com/hc/article_attachments/360066774093/mceclip0.png" alt="mceclip0.png"></p>
<p>We have applied the settings <strong>-eo pipefail</strong> to the bash shell. <strong>-e</strong> tells bash to exit and raise a failure if it encounters any errors. If you are piping commands together bash will typically only raise an error based on the final command of the pipeline. The <strong>-o pipefail </strong>tells bash to raise an error if it encounters one at any point within a pipeline sequence.</p>
<p>Calling commands from within scripts can launch a new shell, which overrides the settings we apply. Or programs can report their error codes incorrectly, and produce success results when they should not. This can commonly happen when you're running your tests within a multi-line run step, as each step executers in a separate shell. You can apply these configurations more explicitly by adding them to the top of your scripts or to the config.yml directly. This can improve the reliability of what is being reported as a failure. </p>
<p>Example:</p>
<pre>- run:<br>    name: run tests<br>    command: |<br>      source venv/bin/activate<br>      python manage.py test</pre>
<p>To work around this add <strong>set -e</strong> at the top of the multiline command. This will ensure that errors are not suppressed and are instead passed up to fail the build.</p>
<pre>- run:<br> name: run tests<br> command: |<br>   set -e<br>   source venv/bin/activate<br>   python manage.py test </pre>